# Generated by Django 3.2.8 on 2021-10-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
